services:
  db:
    image: postgres:16.3
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  backend:
    depends_on:
      - db
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgresql://admin:admin@db:5432
