services:
  db:
    image: postgres:16.3
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
